monitor = HDMI-A-1, 2560x1440, 0x0, 1
monitor = DP-1, 2560x1440, 2560x0, 1


# Make workspaces persistent
# # Odd-numbered workspaces on HDMI-A-1 (second monitor)
workspace = 1, monitor:HDMI-A-1, persistent:true
workspace = 3, monitor:HDMI-A-1, persistent:true
workspace = 5, monitor:HDMI-A-1, persistent:true
workspace = 7, monitor:HDMI-A-1, persistent:true
workspace = 9, monitor:HDMI-A-1, persistent:true

# Even-numbered workspaces on DP-1 (first monitor)
workspace = 2, monitor:DP-1, persistent:true
workspace = 4, monitor:DP-1, persistent:true
workspace = 6, monitor:DP-1, persistent:true
workspace = 8, monitor:DP-1, persistent:true
workspace = 10, monitor:DP-1, persistent:true
