
# ######## Layers and windows rules section ########

# Example windowrule v1
# windowrule = float, ^(kitty)$
# Example windowrule v2
# windowrulev2 = float,class:^(kitty)$,title:^(kitty)$

layerrule {
  name = layerrule-1
  blur = on
  ignore_alpha = 0
  match:namespace = waybar
}


layerrule {
  name = layerrule-2
  blur = on
  ignore_alpha = 0
  match:namespace = notifications
}


layerrule {
  name = layerrule-3
  blur = on
  match:namespace = logout_dialog
}


windowrule {
  name = windowrule-1
  stay_focused = on
  animation = popin 75%
  match:class = ^(wofi)$
}


windowrule {
  name = windowrule-2
  stay_focused = on
  animation = popin 95%
  match:class = ^(emote)$
}


windowrule {
  name = windowrule-3
  stay_focused = on
  match:class = ^(polkit-gnome)$
}


windowrule {
  name = windowrule-4
  workspace = 4
  match:class = ^(Spotify)$
}

windowrule {
  name = windowrule-5
  workspace = 5
  match:class = ^(org.telegram.desktop)$
}

windowrule {
  name = windowrule-6
  workspace = 5
  match:class = ^(vesktop)$
}

windowrule {
  name = windowrule-7
  workspace = 6
  match:class = ^(VirtualBox Manager)$
}


# XDG File Chooser Dialogs
windowrule {
  name = windowrule-8
  stay_focused = on
  size = (monitor_w*0.5) (monitor_h*0.7)
  animation = popin 75%
  center = on
  match:class = ^(xdg-desktop-portal-gtk)$
}


# VirtualBox
windowrule {
  name = windowrule-9
  stay_focused = on
  animation = popin 75%
  center = on
  match:class = ^(VirtualBoxVM)$
}


windowrule {
  name = windowrule-10
  stay_focused = on
  animation = popin 75%
  center = on
  match:class = ^(VirtualBox)$
}


# Generic suppress rule
windowrule {
  name = windowrule-11
  suppress_event = maximize
  match:class = .*
}


