
# ######## Layers and windows rules section ########

# Example windowrule v1
# windowrule = float, ^(kitty)$
# Example windowrule v2
# windowrulev2 = float,class:^(kitty)$,title:^(kitty)$

layerrule = blur, waybar
layerrule = ignorezero, waybar

layerrule = blur, notifications
layerrule = ignorezero, notifications

layerrule = blur, logout_dialog

windowrulev2 = stayfocused, class:^(wofi)$
windowrulev2 = animation popin 75%, class:^(wofi)$

windowrulev2 = stayfocused, class:^(emote)$
windowrulev2 = animation popin 95%, class:^(emote)$

windowrulev2 = stayfocused, class:^(polkit-gnome)$

windowrulev2 = workspace 4, class:^(Spotify)$
windowrulev2 = workspace 5, class:^(org.telegram.desktop)$
windowrulev2 = workspace 5, class:^(vesktop)$
windowrulev2 = workspace 6, class:^(VirtualBox Manager)$

# XDG File Chooser Dialogs
windowrulev2 = stayfocused, class:^(xdg-desktop-portal-gtk)$
windowrulev2 = size 50% 70%, class:^(xdg-desktop-portal-gtk)$
windowrulev2 = animation popin 75%, class:^(xdg-desktop-portal-gtk)$
windowrulev2 = center, class:^(xdg-desktop-portal-gtk)$

# VirtualBox
windowrulev2 = stayfocused, class:^(VirtualBoxVM)$
windowrulev2 = animation popin 75%, class:^(VirtualBoxVM)$
windowrulev2 = center, class:^(VirtualBoxVM)$

windowrulev2 = stayfocused, class:^(VirtualBox)$
windowrulev2 = animation popin 75%, class:^(VirtualBox)$
windowrulev2 = center, class:^(VirtualBox)$

# Generic suppress rule
windowrulev2 = suppressevent maximize, class:.*

